// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-O6AzwVXb6RJP8tMeqkjKY89oGvy9ns',
    appId: '1:222332732786:web:80c2733805de20eaa009eb',
    messagingSenderId: '222332732786',
    projectId: 'fisherds-moviequotes',
    authDomain: 'fisherds-moviequotes.firebaseapp.com',
    databaseURL: 'https://fisherds-moviequotes.firebaseio.com',
    storageBucket: 'fisherds-moviequotes.appspot.com',
    measurementId: 'G-3F6YQVESBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7po5QaRcsgtfg2b2VO3yr-OKj6FXUCrs',
    appId: '1:222332732786:android:681960c81a84c398a009eb',
    messagingSenderId: '222332732786',
    projectId: 'fisherds-moviequotes',
    databaseURL: 'https://fisherds-moviequotes.firebaseio.com',
    storageBucket: 'fisherds-moviequotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIfZ1pTT-bSAHs0lYmLiJlU7VXeS6nXdQ',
    appId: '1:222332732786:ios:06dcf2250a83f514a009eb',
    messagingSenderId: '222332732786',
    projectId: 'fisherds-moviequotes',
    databaseURL: 'https://fisherds-moviequotes.firebaseio.com',
    storageBucket: 'fisherds-moviequotes.appspot.com',
    iosClientId: '222332732786-ftkaq0231djgehl7r1u6mpmh7hs1fbpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieQuotes',
  );
}
