// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-O12-Gg4WfQth9XUT941Rk3gS_PmCpY',
    appId: '1:699702192344:web:2a9ed3226c47bb04ec8fad',
    messagingSenderId: '699702192344',
    projectId: 'flutter-movie-quotes',
    authDomain: 'flutter-movie-quotes.firebaseapp.com',
    storageBucket: 'flutter-movie-quotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJe9O_o5h8oXp3SbYXlYloHTryRgTGXs',
    appId: '1:699702192344:android:9d392d8810ec5454ec8fad',
    messagingSenderId: '699702192344',
    projectId: 'flutter-movie-quotes',
    storageBucket: 'flutter-movie-quotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHgCfoAig-qafJK8DScxfddsMDkG4PlQ',
    appId: '1:699702192344:ios:bd64e694b833dabdec8fad',
    messagingSenderId: '699702192344',
    projectId: 'flutter-movie-quotes',
    storageBucket: 'flutter-movie-quotes.appspot.com',
    iosClientId: '699702192344-ghq3tetfe2buir04cjv5e9oqmclhjh69.apps.googleusercontent.com',
    iosBundleId: 'com.example.myversion',
  );
}
